name: chat_bot
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  shared_preferences: ^2.2.3
  get: ^4.6.5
  get_storage: ^2.1.1
  connectivity_plus: ^3.0.2
  jwt_decoder: ^2.0.1
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.5
  shimmer: ^3.0.0
  flutter_markdown: ^0.7.1
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
  
  fonts:
    - family: Roboto Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
    - family: Roboto Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
